/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { AvailableSlot } from './availableSlot';

/**
 * List of open booking slots.
 */
export interface AvailableSlotsResponse {
  /** Available booking slots. */
  slots?: AvailableSlot[];
}
