/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Available booking slot.
 */
export interface AvailableSlot {
  /** Provider slot identifier. */
  slot_id: string;
  /** Slot start datetime in ISO 8601. */
  starts_at: string;
  /** Slot end datetime in ISO 8601. */
  ends_at: string;
  /** Timezone for this slot. */
  timezone: string;
}
