/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response for avatar creation trigger endpoint.
 */
export interface AvatarCreateResponse {
  /** Replica ID created or reused. */
  replica_id: string;
  /** processing | ready | failed */
  status: string;
  /** Human-readable status message. */
  message: string;
}
