/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { BookingStatus } from './bookingStatus';

/**
 * Created booking payload.
 */
export interface BookingConfirmationResponse {
  /** Booking UUID. */
  booking_id: string;
  /** Related session UUID. */
  session_id: string;
  /** Heart UUID. */
  heart_id: string;
  /** Suitor UUID. */
  suitor_id: string;
  /** External calendar provider booking ID. */
  calcom_booking_id: string;
  /** Scheduled date-time for the booking. */
  scheduled_at: string;
  /** Booking lifecycle state. */
  status: BookingStatus;
  /** Booking creation timestamp. */
  created_at: string;
}
