/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Booked slot display payload.
 */
export interface BookedSlotResponse {
  start: string;
  end: string;
  display: string;
}
