/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Create booking payload.
 */
export interface BookingCreateRequest {
  /** Session UUID being converted to a date booking. */
  session_id: string;
  /** Selected slot datetime in ISO 8601. */
  slot_datetime: string;
}
