/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * cal.com integration health information.
 */
export interface CalcomStatusInfo {
  /** connected | not_configured | error */
  status: string;
  /** Configured cal.com event type ID. */
  event_type_id?: string | null;
}
