/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Calendar status response with lightweight slot preview.
 */
export interface CalendarStatusResponse {
  /** connected | not_configured | error */
  status: string;
  /** Configured event type ID. */
  event_type_id?: string | null;
  /** Preview list of upcoming slot timestamps. */
  slot_preview?: string[];
}
