/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardHeartStatusResponse {
  slug: string;
  name: string;
  active: boolean;
  total_sessions: number;
  link: string;
  deactivated_at?: string | null;
  message?: string | null;
}
