/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardBookingBlock } from './dashboardBookingBlock';
import type { DashboardFeedbackBlock } from './dashboardFeedbackBlock';
import type { DashboardScoresBlock } from './dashboardScoresBlock';
import type { DashboardSessionBlock } from './dashboardSessionBlock';
import type { DashboardSuitorBlock } from './dashboardSuitorBlock';
import type { DashboardTranscriptTurn } from './dashboardTranscriptTurn';

export interface DashboardSessionDetailResponse {
  session_id: string;
  suitor: DashboardSuitorBlock;
  session: DashboardSessionBlock;
  transcript: DashboardTranscriptTurn[];
  scores?: DashboardScoresBlock | null;
  verdict?: 'date' | 'no_date' | null;
  feedback?: DashboardFeedbackBlock | null;
  booking?: DashboardBookingBlock | null;
}
