/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardAvgScores } from './dashboardAvgScores';
import type { DashboardBookingsStats } from './dashboardBookingsStats';
import type { DashboardRecentActivity } from './dashboardRecentActivity';
import type { DashboardScoreDistribution } from './dashboardScoreDistribution';

export interface DashboardStatsResponse {
  total_suitors: number;
  total_sessions: number;
  completed_sessions: number;
  active_sessions: number;
  failed_sessions: number;
  total_dates: number;
  total_rejections: number;
  match_rate: number;
  avg_scores: DashboardAvgScores;
  score_distribution: DashboardScoreDistribution;
  recent_activity: DashboardRecentActivity;
  bookings: DashboardBookingsStats;
}
