/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardBookingBlock {
  booking_id: string;
  cal_event_id: string;
  booked_at: string;
  slot_start: string;
  suitor_email?: string | null;
  suitor_notes?: string | null;
  status: string;
}
