/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export type DashboardSessionSummaryVerdict = typeof DashboardSessionSummaryVerdict[keyof typeof DashboardSessionSummaryVerdict];


export const DashboardSessionSummaryVerdict = {
  date: 'date',
  no_date: 'no_date',
  pending: 'pending',
} as const;
