/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardSessionScores } from './dashboardSessionScores';
import type { DashboardSessionSummaryVerdict } from './dashboardSessionSummaryVerdict';

export interface DashboardSessionSummary {
  session_id: string;
  suitor_name: string;
  suitor_intro?: string | null;
  started_at?: string | null;
  ended_at?: string | null;
  duration_seconds?: number | null;
  status: string;
  questions_asked: number;
  scores?: DashboardSessionScores | null;
  verdict?: DashboardSessionSummaryVerdict;
  has_booking: boolean;
  booking_date?: string | null;
}
