/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardTrendPoint } from './dashboardTrendPoint';
import type { DashboardTrendsResponsePeriod } from './dashboardTrendsResponsePeriod';

export interface DashboardTrendsResponse {
  period: DashboardTrendsResponsePeriod;
  data: DashboardTrendPoint[];
}
