/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardTranscriptTurn {
  turn: number;
  question: string;
  answer: string;
  timestamp: string;
}
