/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardPagination } from './dashboardPagination';
import type { DashboardSessionSummary } from './dashboardSessionSummary';

export interface DashboardSessionsResponse {
  sessions: DashboardSessionSummary[];
  pagination: DashboardPagination;
}
