/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export interface DashboardRecentActivity {
  sessions_today: number;
  sessions_this_week: number;
  sessions_this_month: number;
}
