/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardWeightedScore } from './dashboardWeightedScore';

export interface DashboardScoresBlock {
  effort: DashboardWeightedScore;
  creativity: DashboardWeightedScore;
  intent_clarity: DashboardWeightedScore;
  emotional_intelligence: DashboardWeightedScore;
  aggregate: number;
}
