/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Emotion-based score modifiers.
 */
export interface EmotionModifiers {
  /** Positive weighting from confidence signals. */
  confidence_boost?: number | null;
  /** Negative weighting from hesitation signals. */
  hesitation_penalty?: number | null;
  [key: string]: unknown;
 }
