/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod } from './getDashboardTrendsApiV1DashboardStatsTrendsGetPeriod';

export type GetDashboardTrendsApiV1DashboardStatsTrendsGetParams = {
period?: GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod;
/**
 * @minimum 1
 * @maximum 365
 */
days?: number;
};
