/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export type GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod = typeof GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod[keyof typeof GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod];


export const GetDashboardTrendsApiV1DashboardStatsTrendsGetPeriod = {
  daily: 'daily',
  weekly: 'weekly',
} as const;
