/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export type GetDashboardSessionsApiV1DashboardSessionsGetSortBy = typeof GetDashboardSessionsApiV1DashboardSessionsGetSortBy[keyof typeof GetDashboardSessionsApiV1DashboardSessionsGetSortBy];


export const GetDashboardSessionsApiV1DashboardSessionsGetSortBy = {
  date: 'date',
  score: 'score',
  name: 'name',
} as const;
