/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { GetDashboardSessionsApiV1DashboardSessionsGetSortBy } from './getDashboardSessionsApiV1DashboardSessionsGetSortBy';
import type { GetDashboardSessionsApiV1DashboardSessionsGetSortOrder } from './getDashboardSessionsApiV1DashboardSessionsGetSortOrder';

export type GetDashboardSessionsApiV1DashboardSessionsGetParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
per_page?: number;
verdict?: 'date' | 'no_date' | 'pending' | null;
sort_by?: GetDashboardSessionsApiV1DashboardSessionsGetSortBy;
sort_order?: GetDashboardSessionsApiV1DashboardSessionsGetSortOrder;
search?: string | null;
date_from?: string | null;
date_to?: string | null;
};
