/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export type GetDashboardSessionsApiV1DashboardSessionsGetSortOrder = typeof GetDashboardSessionsApiV1DashboardSessionsGetSortOrder[keyof typeof GetDashboardSessionsApiV1DashboardSessionsGetSortOrder];


export const GetDashboardSessionsApiV1DashboardSessionsGetSortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;
