/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

export type GetSessionSlotsApiV1SessionsIdSlotsGetParams = {
date_from?: string | null;
date_to?: string | null;
};
