/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Payload to activate/deactivate heart link.
 */
export interface LinkToggleRequest {
  /** Whether the public heart link should be active. */
  is_active: boolean;
}
