/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Readiness pre-check before creating a session.
 */
export interface PreCheckResponse {
  can_start: boolean;
  reason?: string | null;
  profile_complete: boolean;
  heart_active: boolean;
  remaining_today: number;
  active_session_id?: string | null;
}
