/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Publicly exposed profile data.
 */
export interface PublicHeartProfileResponse {
  /** Heart display name shown publicly. */
  display_name: string;
  /** Public bio text. */
  bio?: string | null;
  /** Public profile photo URL for the heart. */
  photo_url?: string | null;
  /** Whether the voice interview agent is ready to accept sessions. */
  agent_ready: boolean;
  /** Whether date booking is configured via cal.com. */
  has_calendar: boolean;
  /** Number of screening questions the suitor will answer. */
  question_count: number;
  /** Estimated interview duration from screening question count. */
  estimated_duration: string;
  /** Short personality teaser generated from top persona traits. */
  persona_preview?: string | null;
  /** Whether interview entry is currently accepting new suitors. */
  is_accepting: boolean;
}
