/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Session initialization response payload.
 */
export interface SessionStartResponse {
  /** Created interview session UUID. */
  session_id: string;
  /** LiveKit server URL used by the frontend client. */
  livekit_url: string;
  /** LiveKit JWT for authenticated suitor join. */
  livekit_token: string;
  /** LiveKit room name for this interview session. */
  room_name: string;
  /** Session start status: ready or reconnecting. */
  status: string;
  /** Human-readable start/reconnect message. */
  message: string;
}
