/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Structured feedback payload.
 */
export type SessionVerdictResponseFeedback = { [key: string]: unknown } | null;
