/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Session initialization payload.
 */
export interface SessionStartRequest {
  /** Shareable heart slug used to identify interview target. */
  heart_slug: string;
}
