/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Book a selected slot for a successful date verdict session.
 */
export interface SessionBookRequest {
  slot_start: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  suitor_name: string;
  /**
   * @minLength 3
   * @maxLength 255
   */
  suitor_email: string;
  suitor_notes?: string | null;
}
