/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Session summary item for suitor history.
 */
export interface SessionSummary {
  session_id: string;
  status: string;
  started_at?: string | null;
  ended_at?: string | null;
  duration_seconds?: number | null;
  end_reason?: string | null;
  has_verdict: boolean;
  verdict?: string | null;
}
