/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Polling response for session status.
 */
export interface SessionStatusResponse {
  /** Session UUID. */
  session_id: string;
  /** Session state: pending, in_progress, completed, scoring, scored, expired, failed, cancelled. */
  status: string;
  /** Timestamp when interview started. */
  started_at?: string | null;
  /** Timestamp when interview ended. */
  ended_at?: string | null;
  /** End reason when the session has finished. */
  end_reason?: string | null;
  /** Duration from start to end/current time. */
  duration_seconds?: number | null;
  /** Number of questions asked so far. */
  questions_asked?: number | null;
  /** Total configured screening questions. */
  questions_total?: number | null;
  /** Whether a final verdict exists. */
  has_verdict: boolean;
  /** Verdict pipeline status: pending, scoring, ready. */
  verdict_status?: string | null;
}
