/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { BookedSlotResponse } from './bookedSlotResponse';

/**
 * Booking confirmation payload for suitor.
 */
export interface SessionBookResponse {
  booking_id: string;
  cal_event_id: string;
  slot: BookedSlotResponse;
  status: string;
  message: string;
}
