/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { SlotDayGroup } from './slotDayGroup';

/**
 * Session-scoped slot response used in M6 results flow.
 */
export interface SessionSlotsResponse {
  slots: SlotDayGroup[];
  timezone: string;
  event_duration_minutes: number;
}
