/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { EmotionModifiers } from './emotionModifiers';
import type { Verdict } from './verdict';

/**
 * Final verdict payload returned to suitor.
 */
export interface SessionVerdictResponse {
  /** Session UUID. */
  session_id: string;
  /** Date/no-date verdict. */
  verdict: Verdict;
  /** Overall weighted score (0-100). */
  weighted_total: number;
  /** Effort score (0-100). */
  effort_score: number;
  /** Creativity score (0-100). */
  creativity_score: number;
  /** Intent clarity score (0-100). */
  intent_clarity_score: number;
  /** Emotional intelligence score (0-100). */
  emotional_intelligence_score: number;
  /** Emotion-based score modifiers. */
  emotion_modifiers?: EmotionModifiers | null;
  /** Personalized feedback for the suitor. */
  feedback_text: string;
}
