/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { EmotionModifiers } from './emotionModifiers';
import type { SessionVerdictResponseFeedback } from './sessionVerdictResponseFeedback';
import type { SessionVerdictResponsePerQuestionScores } from './sessionVerdictResponsePerQuestionScores';
import type { SessionVerdictResponseScores } from './sessionVerdictResponseScores';
import type { Verdict } from './verdict';

/**
 * Final verdict payload returned to suitor.
 */
export interface SessionVerdictResponse {
  /** Session UUID. */
  session_id: string;
  /** Verdict status payload: scoring or scored. */
  status: string;
  /** Whether a verdict is ready for this session. */
  ready?: boolean;
  /** Date/no-date verdict. */
  verdict?: Verdict | null;
  /** True only when session verdict is date. */
  booking_available?: boolean | null;
  /** Authenticated suitor name. */
  suitor_name?: string | null;
  /** Heart display name. */
  heart_name?: string | null;
  /** Status message for scoring state. */
  message?: string | null;
  /** Structured weighted scoring payload. */
  scores?: SessionVerdictResponseScores;
  /** Structured feedback payload. */
  feedback?: SessionVerdictResponseFeedback;
  /** Overall weighted score (0-100). */
  weighted_total?: number | null;
  /** Weighted score before emotion modifier. */
  raw_score?: number | null;
  /** Final score after emotion modifier (0-100). */
  final_score?: number | null;
  /** Effort score (0-100). */
  effort_score?: number | null;
  /** Creativity score (0-100). */
  creativity_score?: number | null;
  /** Intent clarity score (0-100). */
  intent_clarity_score?: number | null;
  /** Emotional intelligence score (0-100). */
  emotional_intelligence_score?: number | null;
  /** Emotion-based score modifiers. */
  emotion_modifiers?: EmotionModifiers | null;
  /** Human-readable reasons for emotion modifier. */
  emotion_modifier_reasons?: string[] | null;
  /** Personalized feedback for the suitor. */
  feedback_text?: string | null;
  /** Top strengths identified during scoring. */
  feedback_strengths?: string[] | null;
  /** Top areas for improvement. */
  feedback_improvements?: string[] | null;
  /** Per-question scoring breakdown. */
  per_question_scores?: SessionVerdictResponsePerQuestionScores;
}
