/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { SlotTimeItem } from './slotTimeItem';

/**
 * Slots grouped by date for frontend rendering.
 */
export interface SlotDayGroup {
  date: string;
  day_label: string;
  times: SlotTimeItem[];
}
