/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { SessionSummary } from './sessionSummary';

/**
 * Authenticated suitor session history response.
 */
export interface SuitorSessionsResponse {
  sessions: SessionSummary[];
  total: number;
  daily_limit: number;
  remaining_today: number;
}
