/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Suitor profile completion payload after Clerk authentication.
 */
export interface SuitorRegisterRequest {
  /**
   * Suitor display name for the interview.
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Suitor's age (must be 18+).
   * @minimum 18
   * @maximum 100
   */
  age: number;
  /**
   * Suitor's gender identity.
   * @minLength 1
   * @maxLength 50
   */
  gender: string;
  /**
   * Suitor's orientation.
   * @minLength 1
   * @maxLength 50
   */
  orientation: string;
  /** Optional intro message. */
  intro_message?: string | null;
}
