/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Suitor self-profile response.
 */
export interface SuitorProfileResponse {
  /** Suitor UUID. */
  id: string;
  /** Suitor display name from Clerk profile. */
  name: string;
  /** Suitor email. */
  email?: string | null;
  /** Suitor age. */
  age?: number | null;
  /** Suitor gender identity. */
  gender?: string | null;
  /** Suitor orientation. */
  orientation?: string | null;
  /** Optional intro message. */
  intro_message?: string | null;
  /** Profile creation timestamp. */
  created_at: string;
  /** Profile update timestamp. */
  updated_at: string;
  /** Whether required profile fields are complete. */
  readonly is_profile_complete: boolean;
}
