/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */
import type { CalcomStatusInfo } from './calcomStatusInfo';
import type { TavusStatusInfo } from './tavusStatusInfo';

/**
 * Top-level system health response.
 */
export interface SystemHealthResponse {
  /** healthy | degraded | unhealthy */
  status: string;
  /** Whether a Heart record is available in DB. */
  heart_loaded: boolean;
  /** Current heart display name. */
  heart_name?: string | null;
  /** Current heart shareable slug. */
  heart_slug?: string | null;
  /** connected | error */
  database: string;
  /** connected | error */
  redis: string;
  /** Tavus subsystem health details. */
  tavus: TavusStatusInfo;
  /** cal.com subsystem health details. */
  calcom: CalcomStatusInfo;
}
