/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Tavus replica health information.
 */
export interface TavusStatusInfo {
  /** not_started | processing | ready | failed */
  status: string;
  /** Current Tavus replica ID if available. */
  replica_id?: string | null;
}
