/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Valentine Hotline API
 * AI-powered dating screening system API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Final matchmaking verdict.
 */
export type Verdict = typeof Verdict[keyof typeof Verdict];


export const Verdict = {
  date: 'date',
  no_date: 'no_date',
} as const;
