"""add_heart_deactive

Revision ID: 443b26386e80
Revises: b36aff49f07e
Create Date: 2026-02-14 22:22:27.885364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "443b26386e80"
down_revision: Union[str, Sequence[str], None] = "b36aff49f07e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hearts", sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hearts", "deactivated_at")
    # ### end Alembic commands ###
