"""add_feedback_and_booking

Revision ID: 6f197413d9db
Revises: bdd57d9128c7
Create Date: 2026-02-14 21:38:35.021518

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6f197413d9db"
down_revision: Union[str, Sequence[str], None] = "bdd57d9128c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings", sa.Column("suitor_email", sa.String(length=255), nullable=True)
    )
    op.add_column("bookings", sa.Column("suitor_notes", sa.Text(), nullable=True))
    op.add_column(
        "bookings",
        sa.Column(
            "notification_sent", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "bookings",
        sa.Column(
            "booking_status",
            sa.String(length=50),
            server_default="confirmed",
            nullable=False,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "feedback_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scores", "feedback_json")
    op.drop_column("bookings", "booking_status")
    op.drop_column("bookings", "notification_sent")
    op.drop_column("bookings", "suitor_notes")
    op.drop_column("bookings", "suitor_email")
    # ### end Alembic commands ###
