"""add_suitor_persona

Revision ID: 83808441e2aa
Revises: c9ca9dbd3e75
Create Date: 2026-02-14 10:39:42.684743

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83808441e2aa"
down_revision: Union[str, Sequence[str], None] = "c9ca9dbd3e75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hearts",
        "clerk_user_id",
        existing_type=sa.String(length=255),
        nullable=True,
    )
    op.alter_column(
        "hearts",
        "email",
        existing_type=sa.String(length=320),
        nullable=True,
    )
    op.add_column(
        "suitors", sa.Column("clerk_user_id", sa.String(length=255), nullable=True)
    )
    op.add_column("suitors", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("suitors", sa.Column("gender", sa.String(length=50), nullable=True))
    op.add_column(
        "suitors", sa.Column("orientation", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "suitors",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_suitors_clerk_user_id"), "suitors", ["clerk_user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suitors_clerk_user_id"), table_name="suitors")
    op.drop_column("suitors", "updated_at")
    op.drop_column("suitors", "orientation")
    op.drop_column("suitors", "gender")
    op.drop_column("suitors", "age")
    op.drop_column("suitors", "clerk_user_id")
    op.alter_column(
        "hearts",
        "email",
        existing_type=sa.String(length=320),
        nullable=False,
    )
    op.alter_column(
        "hearts",
        "clerk_user_id",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
