"""remove_hume

Revision ID: b36aff49f07e
Revises: 6f197413d9db
Create Date: 2026-02-14 22:00:54.898238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b36aff49f07e"
down_revision: Union[str, Sequence[str], None] = "6f197413d9db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversation_turns", "emotion_data")
    op.drop_column("scores", "emotion_modifier")
    op.drop_column("scores", "emotion_modifiers")
    op.drop_column("scores", "emotion_modifier_reasons")
    op.drop_column("sessions", "emotion_timeline")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "emotion_timeline",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "emotion_modifier_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "emotion_modifiers",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "emotion_modifier",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("'0'::double precision"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "conversation_turns",
        sa.Column(
            "emotion_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
