"""add_scoring

Revision ID: bdd57d9128c7
Revises: 41bbcc955fde
Create Date: 2026-02-14 20:20:44.294409

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bdd57d9128c7"
down_revision: Union[str, Sequence[str], None] = "41bbcc955fde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores",
        sa.Column("emotion_modifier", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "scores",
        sa.Column(
            "emotion_modifier_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "scores", sa.Column("raw_score", sa.Float(), server_default="0", nullable=False)
    )
    op.add_column(
        "scores",
        sa.Column("final_score", sa.Float(), server_default="0", nullable=False),
    )
    op.add_column(
        "scores",
        sa.Column("verdict_threshold", sa.Float(), server_default="65", nullable=False),
    )
    op.add_column(
        "scores",
        sa.Column("feedback_summary", sa.Text(), server_default="", nullable=False),
    )
    op.add_column(
        "scores",
        sa.Column(
            "feedback_strengths",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "feedback_improvements",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column("scores", sa.Column("feedback_heart_note", sa.Text(), nullable=True))
    op.add_column(
        "scores",
        sa.Column(
            "per_question_scores",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "claude_model",
            sa.String(length=128),
            server_default="claude-sonnet-4-20250514",
            nullable=False,
        ),
    )
    op.add_column(
        "scores", sa.Column("claude_input_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "scores", sa.Column("claude_output_tokens", sa.Integer(), nullable=True)
    )
    op.add_column(
        "scores", sa.Column("scoring_duration_ms", sa.Integer(), nullable=True)
    )
    op.add_column(
        "sessions",
        sa.Column("has_verdict", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "sessions",
        sa.Column(
            "verdict_status",
            sa.String(length=32),
            server_default="pending",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "verdict_status")
    op.drop_column("sessions", "has_verdict")
    op.drop_column("scores", "scoring_duration_ms")
    op.drop_column("scores", "claude_output_tokens")
    op.drop_column("scores", "claude_input_tokens")
    op.drop_column("scores", "claude_model")
    op.drop_column("scores", "per_question_scores")
    op.drop_column("scores", "feedback_heart_note")
    op.drop_column("scores", "feedback_improvements")
    op.drop_column("scores", "feedback_strengths")
    op.drop_column("scores", "feedback_summary")
    op.drop_column("scores", "verdict_threshold")
    op.drop_column("scores", "final_score")
    op.drop_column("scores", "raw_score")
    op.drop_column("scores", "emotion_modifier_reasons")
    op.drop_column("scores", "emotion_modifier")
    # ### end Alembic commands ###
