"""add_other_schemas

Revision ID: c9ca9dbd3e75
Revises: 6c66fe9f5302
Create Date: 2026-02-14 09:38:02.908706

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9ca9dbd3e75"
down_revision: Union[str, Sequence[str], None] = "6c66fe9f5302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hearts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("photo_url", sa.String(length=1024), nullable=True),
        sa.Column("video_url", sa.String(length=1024), nullable=True),
        sa.Column("tavus_avatar_id", sa.String(length=255), nullable=True),
        sa.Column("persona", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "expectations", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("calcom_user_id", sa.String(length=255), nullable=True),
        sa.Column("calcom_event_type_id", sa.String(length=255), nullable=True),
        sa.Column("shareable_slug", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_hearts_clerk_user_id"), "hearts", ["clerk_user_id"], unique=True
    )
    op.create_index(op.f("ix_hearts_email"), "hearts", ["email"], unique=True)
    op.create_index(
        op.f("ix_hearts_shareable_slug"), "hearts", ["shareable_slug"], unique=True
    )
    op.create_table(
        "suitors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("intro_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_suitors_email"), "suitors", ["email"], unique=False)
    op.create_table(
        "screening_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("heart_id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["heart_id"], ["hearts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_questions_heart_id"),
        "screening_questions",
        ["heart_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_questions_order_index"),
        "screening_questions",
        ["order_index"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("heart_id", sa.UUID(), nullable=False),
        sa.Column("suitor_id", sa.UUID(), nullable=False),
        sa.Column("livekit_room_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="session_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["heart_id"], ["hearts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suitor_id"], ["suitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_heart_id"), "sessions", ["heart_id"], unique=False
    )
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_index(
        op.f("ix_sessions_suitor_id"), "sessions", ["suitor_id"], unique=False
    )
    op.create_table(
        "bookings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("heart_id", sa.UUID(), nullable=False),
        sa.Column("suitor_id", sa.UUID(), nullable=False),
        sa.Column("calcom_booking_id", sa.String(length=255), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "CANCELLED", "RESCHEDULED", name="booking_status"),
            server_default="CONFIRMED",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["heart_id"], ["hearts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suitor_id"], ["suitors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookings_calcom_booking_id"),
        "bookings",
        ["calcom_booking_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_heart_id"), "bookings", ["heart_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_scheduled_at"), "bookings", ["scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_session_id"), "bookings", ["session_id"], unique=False
    )
    op.create_index(op.f("ix_bookings_status"), "bookings", ["status"], unique=False)
    op.create_index(
        op.f("ix_bookings_suitor_id"), "bookings", ["suitor_id"], unique=False
    )
    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column(
            "speaker",
            sa.Enum("AVATAR", "SUITOR", name="conversation_speaker"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "emotion_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_turns_session_id"),
        "conversation_turns",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_turns_speaker"),
        "conversation_turns",
        ["speaker"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_turns_turn_index"),
        "conversation_turns",
        ["turn_index"],
        unique=False,
    )
    op.create_table(
        "scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("effort_score", sa.Float(), nullable=False),
        sa.Column("creativity_score", sa.Float(), nullable=False),
        sa.Column("intent_clarity_score", sa.Float(), nullable=False),
        sa.Column("emotional_intelligence_score", sa.Float(), nullable=False),
        sa.Column("weighted_total", sa.Float(), nullable=False),
        sa.Column(
            "emotion_modifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "verdict", sa.Enum("DATE", "NO_DATE", name="verdict"), nullable=False
        ),
        sa.Column("feedback_text", sa.Text(), nullable=False),
        sa.Column("raw_llm_response", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scores_session_id"), "scores", ["session_id"], unique=True)
    op.create_index(op.f("ix_scores_verdict"), "scores", ["verdict"], unique=False)
    op.create_index(
        op.f("ix_scores_weighted_total"), "scores", ["weighted_total"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scores_weighted_total"), table_name="scores")
    op.drop_index(op.f("ix_scores_verdict"), table_name="scores")
    op.drop_index(op.f("ix_scores_session_id"), table_name="scores")
    op.drop_table("scores")
    op.drop_index(
        op.f("ix_conversation_turns_turn_index"), table_name="conversation_turns"
    )
    op.drop_index(
        op.f("ix_conversation_turns_speaker"), table_name="conversation_turns"
    )
    op.drop_index(
        op.f("ix_conversation_turns_session_id"), table_name="conversation_turns"
    )
    op.drop_table("conversation_turns")
    op.drop_index(op.f("ix_bookings_suitor_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_status"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_session_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_scheduled_at"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_heart_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_calcom_booking_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_sessions_suitor_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_heart_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(
        op.f("ix_screening_questions_order_index"), table_name="screening_questions"
    )
    op.drop_index(
        op.f("ix_screening_questions_heart_id"), table_name="screening_questions"
    )
    op.drop_table("screening_questions")
    op.drop_index(op.f("ix_suitors_email"), table_name="suitors")
    op.drop_table("suitors")
    op.drop_index(op.f("ix_hearts_shareable_slug"), table_name="hearts")
    op.drop_index(op.f("ix_hearts_email"), table_name="hearts")
    op.drop_index(op.f("ix_hearts_clerk_user_id"), table_name="hearts")
    op.drop_table("hearts")
    # ### end Alembic commands ###
