"""add_livkit_session

Revision ID: e6de850da091
Revises: 83808441e2aa
Create Date: 2026-02-14 11:48:25.735680

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6de850da091"
down_revision: Union[str, Sequence[str], None] = "83808441e2aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hearts", sa.Column("tavus_persona_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("livekit_room_sid", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("end_reason", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "sessions",
        sa.Column(
            "turn_summaries", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column(
        "sessions", sa.Column("audio_recording_url", sa.Text(), nullable=True)
    )
    op.create_index(
        op.f("ix_sessions_livekit_room_sid"),
        "sessions",
        ["livekit_room_sid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_livekit_room_sid"), table_name="sessions")
    op.drop_column("sessions", "audio_recording_url")
    op.drop_column("sessions", "turn_summaries")
    op.drop_column("sessions", "end_reason")
    op.drop_column("sessions", "livekit_room_sid")
    op.drop_column("hearts", "tavus_persona_id")
    # ### end Alembic commands ###
